import type { GenerateQuizQuestionsInput } from '@/ai/flows/generate-quiz-questions';
import type { Timestamp } from 'firebase/firestore';

export interface QuizQuestion {
  id: string; // Unique ID for the question (e.g., generated UUID)
  question: string;
  options: string[];
  correctAnswer: string;
  userAnswer?: string;
  isCorrect?: boolean; // Determined after user answers
}

export type QuizTerminationReason = "completed" | "time_up" | "cheating";

export interface Quiz {
  id: string; // Unique ID for the quiz (e.g., generated UUID)
  topic: string;
  subtopic?: string; // Optional: Specific subtopic
  difficulty: 'easy' | 'medium' | 'hard';
  questions: QuizQuestion[];
  config: GenerateQuizQuestionsInput; // Original input to AI, now includes new fields
  createdAt: number; // Timestamp
  startedAt?: number; // Optional: Timestamp when the quiz was first started/loaded by the user for timed quizzes
  score?: number; // Calculated after completion
  completedAt?: number; // Timestamp
  currentQuestionIndex: number; // To track progress
  timeLimitMinutes?: number; // Optional: total quiz time limit in minutes, from form
  perQuestionTimeSeconds?: number; // Optional: calculated time per question if total time limit is set
  totalTimeTaken?: number; // Optional: seconds
  challengerName?: string; // Optional: name of the user who challenged
  additionalInstructions?: string; // Optional: instructions given to AI
  isPublic?: boolean; // Optional: whether the quiz is public
  quizTerminationReason?: QuizTerminationReason;
  cheatingFlags?: number;
}

export interface SocialLinks {
  github?: string;
  linkedin?: string;
  instagram?: string;
}

export interface UserProfile {
  uid: string; // From Firebase Auth
  email: string | null; // From Firebase Auth
  displayName?: string | null; // From Firebase Auth & Firestore
  photoURL?: string | null; // From Firebase Auth & Firestore
  bio: string; 
  birthdate: string; // ISO string "YYYY-MM-DD"
  socialLinks?: SocialLinks; // Firestore
  createdAt?: number | Timestamp; 
  updatedAt?: number | Timestamp; 
  totalScore?: number; // Aggregated score for leaderboard
  quizzesCompleted?: number; // Count of completed quizzes for leaderboard
  lastLoginAt?: Timestamp; // Timestamp of the last login
  loginHistory?: string[]; // Array of 'YYYY-MM-DD' date strings for unique login days
  currentStreak?: number; // Current daily login streak
  lastStreakLoginDate?: string; // 'YYYY-MM-DD' of the last login that counted for the streak
}

// Data structure for Firestore 'users' collection documents
export interface UserProfileFirestoreData {
  displayName?: string;
  photoURL?: string;
  bio: string; 
  birthdate: string; // ISO string "YYYY-MM-DD"
  socialLinks?: SocialLinks;
  email?: string; 
  createdAt?: number | Timestamp; 
  updatedAt?: number | Timestamp; 
  totalScore?: number; 
  quizzesCompleted?: number; 
  lastLoginAt?: Timestamp;
  loginHistory?: string[];
  currentStreak?: number;
  lastStreakLoginDate?: string;
}

export type ActivityType = 'tab_switch' | 'fullscreen_exit' | 'copy_attempt' | 'paste_attempt' | 'context_menu' | 'motion_detected';

export interface CheatingActivityLog {
  id?: string; // Auto-generated by Firestore
  userId: string;
  quizId: string;
  activityType: ActivityType;
  timestamp: Timestamp;
  details?: string; // Optional additional details
}
